"""This is randoworde - a script for pseudo-random pseudo-words.

This script generate some pseudo-random pseudo-words from a
dictionary of words.

"""
import random
import sys


def read_words(wordfile='words.txt'):
    """Load words from the dictionary + filter out some."""
    words = []
    with open(wordfile, 'r') as inputfile:
        for lines in inputfile:
            word = lines.strip().lower()
            if word.find("'") == -1 and len(word) >= 2:
                words.append(lines.strip().lower())
    return words


def random_word(words, maxw=3):
    """Generate a raondom word from a given numer of words.

    The random word is generated by selection n words randomly from
    a list of words. Then, for each word, the first k letters are
    selected and joined to create the final word.

    Parameters
    ----------
    words : list of strings
        A dictionary of words to select from.
    maxw : integer
        The number of words to select and combine.

    Returns
    -------
    out : string
        The random word created.

    """
    maxw = max(2, maxw)
    nwords = random.randint(2, maxw)
    rwords = random.sample(words, nwords)
    new_word = []
    for word in rwords:
        idx = random.randint(2, len(word))
        new_word.append(word[:idx])
    return ''.join(new_word)


def main(nword):
    """Create some words and print them to the screen.

    Parameters
    ----------
    nword : integer
        The number of words to create.

    Returns
    -------
    gen_words : list of strings
        The words generated.

    """
    words = read_words()
    gen_words = []
    for _ in range(nword):
        word = random_word(words, maxw=2)
        gen_words.append(word)
        print(word)
    return gen_words


if __name__ == '__main__':  # pragma: no cover
    try:
        WRDS = int(sys.argv[1])
    except IndexError:
        WRDS = 1
    except ValueError:
        WRDS = 1
    main(WRDS)
